### PR TITLE
Fix provider to take table-name when querying secret.

### PR DESCRIPTION
**Pull request by lomkju**
With one provider you can query multiple tables.

### CODE REVIEW

**Comment by tmichel** [comment]
I'm not sure that this is needed when you can have multiple instances of a provider with different configuration: https://www.terraform.io/docs/configuration/providers.html#multiple-provider-instances

I'd much rather keep the provider simple than to have functionality that duplicates what terraform offers out of the box. 

Maybe a note in the README to point folks in the right direction would help since having multiple credstash tables is pretty common I guess. Let me know what you think.

**Comment by lomkju** [comment]
Yes we can do that. We wanted this because we wanted to pass dynamic strings as the table-name and provider didn't allow locals to be passed. Only variables are allowed in the provider block.

**Comment by tmichel** [comment]
Thanks for the fixed build!

Can you please revert the `Makefile` and `.gitignore` files to their original state? Also if you could add a note to the README about how to override the `table` that would be superb. 

After these we can merge this pull request.

**Comment by tmichel** [comment]
Thanks! I'll merge the PR and release a new version soon.

**Pull request merged**
